### ISSUE TITLE
[Query] What is the purpose of having -H flag on ballerina docker command

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/container-support#17]
As per the [1] and [2], Users can run ballerina docker command as below.

[2]

> asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina docker --help
> Dockerize Ballerina programs
> 
> Usage:
> 
> ballerina docker <package-file-path> [--tag | -t <image-name>] [--host | -H <hostURL>] --help | -h --yes | -y
> 
> Flags:
> 	--tag, -t
> 	--host, -H
> 	--yes, -y
> 	--help, -h

What is the purpose of having -H flag.

I am observing -H flag with following:

> asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina docker /home/asankav/svn/ballerina_test/services/artifacts/wokerSupport/workerservice.bsz -t dockimage -H http://0.0.0.0:2379
> ballerina: build docker image [dockimage:latest] in docker host [http://0.0.0.0:2379]? (y/n): y
> Building Docker image dockimage:latest...
> ballerina: error executing: GET at: http://0.0.0.0:2379/images/json?all=false. Cause: Failed to connect to /0.0.0.0:2379

[1]https://github.com/ballerinalang/container-support/releases/tag/v0.8.0-ALPHA

**Comment by chamilad** [comment]
Please reopen if you have any further questions.
