### ISSUE TITLE
Latest docker image not found in dockerhub

### ISSUE THREAD

**Issue by lasinducharith** [ballerinalang/container-support#76]
$ballerina docker helloService.bal 

Build docker image [helloservice:latest] in docker host [localhost]? (y/n): y
ballerina: Docker image build failed for image helloservice.latest : Tag 0.95.1-SNAPSHOT not found in repository docker.io/ballerinalang/ballerina

**Comment by djkevincr** [comment]
We don't push Ballerina docker images for snapshot versions. Public Docker Hub only contains  base images for Ballerina runtime released versions. 

However if you want to create image using a base image of snapshot runtime version, then you need to build base image first by following command.

container-support/ballerina-base-image$ ./build.sh -d ../../ballerina-0.95.1-SNAPSHOT.zip -v 0.95.1-SNAPSHOT -o ballerinalang
